// Generated by IcedCoffeeScript 1.6.3-g
(function() {
  var Engine, argv, iced, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  Engine = require('../lib/engine').Engine;

  argv = require('optimist').demand(1).alias('a', 'assign-to').describe('a', 'Output JS and assign to the given variable').argv;

  exports.main = function() {
    var engine, err, file, output, records, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    file = argv._[0];
    engine = new Engine(file);
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "src/main.iced",
        funcname: "main"
      });
      engine.run(__iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            err = arguments[0];
            return records = arguments[1];
          };
        })(),
        lineno: 12
      }));
      __iced_deferrals._fulfill();
    })(function() {
      if (typeof err !== "undefined" && err !== null) {
        console.error(err);
        sys.exit(-1);
      }
      output = JSON.stringify(records, null, 4);
      if (argv.a != null) {
        output = argv.a + " = " + output + ";";
      }
      return console.log(output);
    });
  };

}).call(this);
